CAAMAR/config/routes.rb
Rails.application.routes.draw do
  resources :usuarios do
    post 'getJson', on: :collection
  end
  resources :sessions

  root 'sessions#new'

  get '/definir-senha/:id', to: 'auth#define_password'
  get '/runner/add', to: 'runner#add'

  get 'gerenciamento', to: 'gerenciamento#index'
  get 'gerenciamento/templates', to: 'gerenciamento#show_templates'
  get 'gerenciamento/results_popup'
  get 'gerenciamento/generate_csv'

  get 'turmas', to: 'turmas#index'

  get 'avaliacoes', to: 'avaliacoes#index'

  get 'uploader', to: 'uploader#index'

  get 'template', to: 'template#index'
  get 'getemps', to: 'gerenciamento#show_templates'
  get 'template/edit', to: 'template#edit'
  get 'edit_template', to: 'template#edit_template', as: 'edit_template'

  post 'edit_template', to: 'template#edit'

  post 'delete_template', to: 'template#delete_template', as: 'delete_template'

  get "statistics", to: "forms_statiscis#index"
  resources :forms_statiscis do
    get :form, on: :collection
  end

  # resource to read json files
  resources :jsonfiles do
    collection do
      post :import
    end
  end

  # resource to create forms
  resource :formcreates do
    collection do
        post :import
    end
  end

  # resource to suposebly create template
  resource :templatecreates do
    collection do
      post :import
    end
  end

  resource :template do
    collection do
      post :edit
    end
  end

  #
  get 'forms_answer/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'forms_answer/new/:form_id/:solver_id', to: 'forms_answer#new'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  post '/import_formanswercreates', to: 'forms_answer#create', as: 'import_formanswercreates'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

CAAMAR/app/controllers/turmas_controller.rb
class TurmasController < ApplicationController
  def index
    unless helpers.is_user_admin()
        redirect_to "/"
        return
    end
    
    @json_classes = []
    @json_templates = []

    path = 'db/json/classes.json'
    if File.file?(path)
      @json_classes = JSON.parse(File.read(path))
    end

    path2 = 'db/json/templates.json'
    if File.file?(path2)
      @json_templates = JSON.parse(File.read(path2))
    end
  end
end

CAAMAR/app/helpers/turmas_helper.rb
module TurmasHelper
end

CAAMAR/app/views/turmas/index.html.erb
<%= render '/navbar/navbar' %>

<h1>Turmas</h1>

<div class="grid-container">

    <% @json_classes.each do |e| %>
        <div class="card">
            <h2> <%= e["name"] %> </h2>

            <%= form_with url: import_formcreates_path, method: :post do |f| %>
            
            <div class="field">
                <%= f.label "Código:" %>
                <%= f.text_field :codigo, value: e["code"], readonly: true %>
            </div>
            <div class="field">
                <%= f.label "Semestre:" %>
                <%= f.text_field :semestre, value: e["class"]["semester"], readonly: true %>
            </div>
            <div class="field">
                <%= f.label "Turma:" %>
                <%= f.text_field :turma, value: e["class"]["classCode"], readonly: true %>
            </div>
            <div class="field">
                <%= f.label "Horário:" %>
                <%= f.text_field :horario, value: e["class"]["time"], readonly: true %>
            </div>

            <h4> Escolha o destinatário: </h4>
            <div class="field">
                <%= f.radio_button :tipo, "discente", required: true %>
                <%= f.label "discente" %>
                <%= f.radio_button :tipo, "docente", required: true %>
                <%= f.label "docente" %>
            </div>

            <h4> Escolha o template: </h4>
            <div class="field">
                <% @json_templates.each do |t| %>
                    <% if t["active"] == 1 %>
                        <p>
                            <%= f.radio_button :id, t["id"], required: true %>
                            <%= f.label t["name"] %>
                        </p>
                    <% end %>
                <% end %>
            </div>

            <%= f.submit "Enviar formulário", class: "btn btn-primary" %>
            <% end %>
        </div>
    <% end %>

</div>