CAAMAR/config/routes.rb
Rails.application.routes.draw do
  resources :usuarios do
    post 'getJson', on: :collection
  end
  resources :sessions

  root 'sessions#new'

  get '/definir-senha/:id', to: 'auth#define_password'
  get '/runner/add', to: 'runner#add'

  get 'gerenciamento', to: 'gerenciamento#index'
  get 'gerenciamento/templates', to: 'gerenciamento#show_templates'
  get 'gerenciamento/results_popup'
  get 'gerenciamento/generate_csv'

  get 'turmas', to: 'turmas#index'

  get 'avaliacoes', to: 'avaliacoes#index'

  get 'uploader', to: 'uploader#index'

  get 'template', to: 'template#index'
  get 'getemps', to: 'gerenciamento#show_templates'
  get 'template/edit', to: 'template#edit'
  get 'edit_template', to: 'template#edit_template', as: 'edit_template'

  post 'edit_template', to: 'template#edit'

  post 'delete_template', to: 'template#delete_template', as: 'delete_template'

  get "statistics", to: "forms_statiscis#index"
  resources :forms_statiscis do
    get :form, on: :collection
  end

  # resource to read json files
  resources :jsonfiles do
    collection do
      post :import
    end
  end

  # resource to create forms
  resource :formcreates do
    collection do
        post :import
    end
  end

  # resource to suposebly create template
  resource :templatecreates do
    collection do
      post :import
    end
  end

  resource :template do
    collection do
      post :edit
    end
  end

  #
  get 'forms_answer/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'forms_answer/new/:form_id/:solver_id', to: 'forms_answer#new'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  post '/import_formanswercreates', to: 'forms_answer#create', as: 'import_formanswercreates'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

CAAMAR/app/controllers/forms_answer_controller.rb
class FormsAnswerController < ApplicationController
  def index

  end


  def new
    @forms = JSON.parse(File.read("db/json/forms.json"))
    templates = JSON.parse(File.read("db/json/templates.json"))
    @form = @forms.find {|form| form["id"] == params[:form_id].to_i}
    @template = templates.find {|template| template["id"] == @form["template_id"].to_i}
    puts @template, params[:id]


  end

  def create
    answers_file_path = "db/json/answers.json"
    forms_file_path = "db/json/forms.json"
    @forms = JSON.parse(File.read(forms_file_path))
    @form = @forms.find {|form| form["id"] == params[:form_id].to_i}
    solver = @form["solvers"].find { |solver| solver["id"] == params[:solver_id].to_i }
    solver["is_solved"] = true
    File.write(forms_file_path, JSON.pretty_generate(@forms))
    if File.file?(answers_file_path)
      @answers = JSON.parse(File.read(answers_file_path))
      answer_id = @answers.map {|answer| answer["id"]}.max || 0
      answer_id += 1
    else
      @answers = JSON.parse("{}")
      answer_id = 1
    end
    answer_hash = {"id" => answer_id}
    personal_answers = []
    params.each do |key, value|
      next if  key != "form_id" && key.to_i.to_s != key # Ignorar essas chaves
      if key.to_i.to_s == key
        if value.to_i.to_s == value
          personal_answers.push({"question_id" => key.to_i, "answer" => value.to_i})

        else
          personal_answers.push({"question_id" => key.to_i, "answer" => value})
        end

      else
        if value.to_i.to_s == value
          answer_hash[key] = value.to_i
        else
          answer_hash[key] = value
        end

      end
    end
    answer_hash["questions"] = personal_answers
    @answers << answer_hash
    puts "esse é o hash #{personal_answers}"
    File.write(answers_file_path, JSON.pretty_generate(@answers))
  end


end

CAAMAR/app/views/forms_answer/create.html.erb
<h1>RESPOSTA ENVIADA</h1>

CAAMAR/app/views/forms_answer/index.html.erb
<h1>FormsAnswer#index</h1>
<p>Find me in app/views/forms_answer/index.html.erb</p>

CAAMAR/app/views/forms_answer/new.html.erb
<h1><%="Respondendo Formulário #{params[:form_id]}" %></h1>

<%= form_with url: import_formanswercreates_path, method: :post do |f| %>
    <%= f.label "Código:" %>
    <%= f.text_field :form_id, value:params[:form_id], readonly: true %>
    <%= f.label "solver:" %>
    <%= f.text_field :solver_id, value:params[:solver_id], readonly: true %>


  <% @template["questions"].each do |question| %>
    <%symbol_reference = question["id"].to_s.to_sym %>
    <div class="field">
      <% if question["type"] == "open" %>
        <P><%= f.label "#{question["id"]})  #{question["prompt"]} :" %>
        <P><%= f.text_field symbol_reference, required: true %></P></P>
      <% elsif question["type"] == "radio_button" %>
        <P><%= f.label "#{question["id"]})  #{question["prompt"]} :" %>
        <% question["options"].each do |option| %>
           <P> <%= f.radio_button symbol_reference, option.to_s,id: "option_#{option}", required: true%>
          <%= f.label "option_#{option}", option.to_s %></P></P>
        <% end %>
      <% end %>
    </div>
  <% end %>
  <%= f.submit "Salvar" %>
<% end %>