CAAMAR/config/routes.rb
Rails.application.routes.draw do
  resources :usuarios do
    post 'getJson', on: :collection
  end
  resources :sessions

  root 'sessions#new'

  get '/definir-senha/:id', to: 'auth#define_password'
  get '/runner/add', to: 'runner#add'

  get 'gerenciamento', to: 'gerenciamento#index'
  get 'gerenciamento/templates', to: 'gerenciamento#show_templates'
  get 'gerenciamento/results_popup'
  get 'gerenciamento/generate_csv'

  get 'turmas', to: 'turmas#index'

  get 'avaliacoes', to: 'avaliacoes#index'

  get 'uploader', to: 'uploader#index'

  get 'template', to: 'template#index'
  get 'getemps', to: 'gerenciamento#show_templates'
  get 'template/edit', to: 'template#edit'
  get 'edit_template', to: 'template#edit_template', as: 'edit_template'

  post 'edit_template', to: 'template#edit'

  post 'delete_template', to: 'template#delete_template', as: 'delete_template'

  get "statistics", to: "forms_statiscis#index"
  resources :forms_statiscis do
    get :form, on: :collection
  end

  # resource to read json files
  resources :jsonfiles do
    collection do
      post :import
    end
  end

  # resource to create forms
  resource :formcreates do
    collection do
        post :import
    end
  end

  # resource to suposebly create template
  resource :templatecreates do
    collection do
      post :import
    end
  end

  resource :template do
    collection do
      post :edit
    end
  end

  #
  get 'forms_answer/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'forms_answer/new/:form_id/:solver_id', to: 'forms_answer#new'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  post '/import_formanswercreates', to: 'forms_answer#create', as: 'import_formanswercreates'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

CAAMAR/app/models/usuario.rb
class Usuario < ApplicationRecord
    validates :matricula, presence: true
    validates :nome, presence: true
    validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
    validates :senha, presence: true
    
    attribute :isAdmin, :boolean, default: false
    attribute :isAluno, :boolean, default: false
    attribute :isProf, :boolean, default: false
    attribute :curso, :string
    attribute :departamento, :string
end

CAAMAR/app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :verify_authenticity_token, :set_usuario, only: %i[ show edit update destroy ]

  # GET /usuarios or /usuarios.json
  # Lista todos os usuários cadastrados.
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1 or /usuarios/1.json
  # Exibe os detalhes de um usuário específico.
  def show
  end

  # GET /usuarios/new
  # Renderiza o formulário para criar um novo usuário.
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  # Renderiza o formulário para criar um novo usuário.
  def edit
  end

  # POST /usuarios or /usuarios.json
  # Cria um novo usuário com base nos parâmetros fornecidos.
  def create
    Rails.logger.info("esse aluno: #{usuario_params}")
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
       # Se o usuário for salvo com sucesso, redireciona para a página do usuário com uma mensagem de sucesso.
        format.html { redirect_to(@usuario, notice: 'User was successfully created.') }
        format.json { render json: @user, status: :created, location: @user }
      else
         # Se houver erros ao salvar, renderiza novamente o formulário de criação com os erros exibidos.
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end
    
  def usuario_params
    params.require(:usuario).permit({:usuario =>[:matricula, :nome, :formacao, :email, :senha,:curso,:isAdmin,:isAluno,:isProf]})
  end

  # PATCH/PUT /usuarios/1 or /usuarios/1.json
  # Atualiza os dados de um usuário existente com base nos parâmetros fornecidos.
  def update

    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to usuario_url(@usuario), notice: "Usuario was successfully updated." }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1 or /usuarios/1.json
  # Remove um usuário existente do sistema.
  def destroy
    @usuario.destroy!

    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: "Usuario was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  #
  ## Pega o arquivo, extrai os alunos e cria usuários no banco
  def getJson
    file = File.read('db/json/class_members.json')
    data_hash = JSON.parse(file)
    alunos = data_hash[0]['dicente']

    alunos.each do |aluno|
      Rails.logger.info("esse aluno: #{aluno}")
      @usuario = Usuario.new(
        matricula: aluno["matricula"],
        nome: aluno["nome"],
        formacao: aluno["formacao"],
        curso: aluno["curso"],
        email: aluno["email"],  
        senha: aluno["senha"]
      )

      if @usuario.save
        Rails.logger.info("deu bom")
      else
        Rails.logger.info("deu ruim")
      end
      
    end
  end

  private
    
    # Configura o usuário com base no parâmetro :id.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Define os parâmetros permitidos para criação/atualização de usuários.
    def usuario_params
      params.require(:usuario).permit(:matricula, :nome, :email, :formacao,:senha,:curso, :isAdmin,:isProf,:isAluno)
    end
end

CAAMAR/app/helpers/usuarios_helper.rb
module UsuariosHelper
end

CAAMAR/app/views/usuarios/_form.html.erb
<!-- app/views/usuarios/_form.html.erb -->
<%= form_with(model: usuario, local: true) do |form| %>
  <% if usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
        <% usuario.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :matricula %>
    <%= form.text_field :matricula %>
  </div>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div class="field">
    <%= form.label :formacao %>
    <%= form.text_field :formacao %>
  </div>

  <div class="field">
    <%= form.label :senha %>
    <%= form.password_field :senha %>
  </div>

  <div class="field">
    <%= form.label :curso %>
    <%= form.text_field :curso %>
  </div>

  <div class="field">
    <%= form.label :isAdmin %>
    <%= form.check_box :isAdmin %>
  </div>

  <div class="field">
    <%= form.label :isProf %>
    <%= form.check_box :isProf %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

CAAMAR/app/views/usuarios/edit.html.erb
<!-- app/views/usuarios/edit.html.erb -->
<h1>Edit Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

CAAMAR/app/views/usuarios/index.html.erb
<!-- app/views/usuarios/index.html.erb -->
<h1>Listing Usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Matricula</th>
      <th>Nome</th>
      <th>Email</th>
      <th>Formacao</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.matricula %></td>
        <td><%= usuario.nome %></td>
        <td><%= usuario.email %></td>
        <td><%= usuario.formacao %></td>
        <td><%= link_to 'Show', usuario %></td>
        <td><%= link_to 'Edit', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Destroy', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usuario', new_usuario_path %>

CAAMAR/app/views/usuarios/new.html.erb
<!-- app/views/usuarios/new.html.erb -->
<h1>New Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Back', usuarios_path %>

CAAMAR/app/views/usuarios/show.html.erb
<!-- app/views/usuarios/show.html.erb -->
<p>
  <strong>Matricula:</strong>
  <%= @usuario.matricula %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @usuario.nome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @usuario.email %>
</p>

<p>
  <strong>Formacao:</strong>
  <%= @usuario.formacao %>
</p>

<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>